twist_mux:
  ros__parameters:
    topics:
      teleop:
        topic   : teleop_cmd_vel
        timeout : 0.5
        priority: 10
      interlock:
        topic   : interlock_cmd_vel
        timeout : 0.5
        priority: 100
